= IDEAS

== The combat system should be interesting
The combat system should be interesting for all types of characters, but not too cumbersome to take too much time to use.

=== Magic
* The caster should be able to cast spells at various levels of potency. e.g. chose the percentage or power-level for a spell when binding to a quick slot. Amount of flexibility could be affected by a "mana-control" proficiency skill.
* Some traits/skills should affect mana points, magic potency, etc.
* stealth could play a part.
* (? could make things over-complicated) charged trinkets could be used to power-up or even cast some spells.

=== Melee
* Strength skill could affect damage, weapon skill should reduce fatigue needed for attacks, dexterity should affect to-hit ratios.
* If wielding a weapon with requirements for another proficiency, a fighter skilled enough in a different proficiency should still get some bonus compared to non-fighters i.e. some skills should default to others at a penalty.
* Possible to enchant the weapon temporarily via magic or potion/salve.
* stealth could play some part.

=== Ranged
* Strength should affect range, proficiency should affect accuracy and fatigue, perception should (?)considerably affect accuracy.
* stealth could play a big part.
* special projectiles (e.g. poison, enchanted arrows, etc)
* weapon could be enchanted and charged to enchant it's on shot for a limited amount shots/time.

=== All
* Potions, charged trinkets, etc to temporarily enhance ability, etc.

== Non-combat Possibilities of Magic Users
Interdimensional storage can lessen or even eliminate the need of pack animals.
Interdimensional travel spells can save a member from a deadly blow or could be used to gain passage to warded areas.
Personal dimension / arcane sanctuary can serve as a safe spot for resting, maybe even training/learning/research at higher levels.

== General Gameplay

=== Aging
The party will definitely age - this would lead to some immersive elements having more sense and impact e.g. training, getting incarcerated, time-passage difference between different dimensions (e.g. mages could use magical dimensions to learn/train a lot and not get much older), seeking for a way to stave-off death or get younger is a nice questing possibility, etc.

== Randomly Generated Content

=== Random generated levels
Could be a good way to level-up and/or find some treasure.

Could be some levels or quests e.g. go find/kill something beneath/close-to this place that causes this place inconvenience/greed/danger.
Other planes e.g. Astral, Arcane plane accessible through some long-forgotten magical door or a higher level spell.

== Misc/Unsorted
* maps
* resting
** fatigue/sleep deprivation
** ? setting up watch
** resting in unsafe areas e.g. waking up to enemy ambush, or waking up to FIREBALLS, etc.
* traps
** traps that transport a character or the entire party e.g. slides, pits, teleports, interplanary/planetary teleports, etc
** traps that summon creatures e.g. raises the nearby skeletons, calls creatures, summons elemental beasts
** traps that lock one in (and you have to solve a puzzle and/or have a special item to get out)
* magic can affect the enfironment (e.g. freezing spells freze swamp water and the party can safely walk over, fire spell sets off explosives/burns spider-webs/destroys monster nests/ etc.)
* providing more than one means to acquire a quest/puzzle item or more than one place to acquire it seems like a good idea for a varied play-through ability (e.g. characters/parties with various strengths), and adds to replay value.
* varied means of transportation between levels/areas (e.g. minecart ride, magnetic tunnel, falling/climbing down a pit)
* additional means of distant travel: horse/carriage/boat/ship/air-ship
* magical means of traveling and moving in general: teleport/fly/water-breathing+water-current/hover
* bows/weapons that can shoot fireballs or other spells (at the expense of stamina?)
* unseen/hidden areas (perception and rogue/tief skills come into play)
* line of sight
* enemies immune to most forms of attack, and enemies that can only be defeated with special artefacts.
* explosives mundane and magical
* trapped chests/doors
* special locks & special keys
* magic warded areas and magic locks on chests & doors
* party members one can rescue
* secret doors
* breakable walls
* magical portals
* dragons
* ancient ruins/castles/dungeons
* magical passage ways to other dimensions
* legendary artefacts (some could be awesome equipment)
* named artefacts especially legendary, unique, rare stuff (i.e. LOTR glamdring, sting, ancient mythril armor could have gained a name as well)

=== the world does not turn around the player
It is quite nice when the characters you control are not the centre of the world around them. It is only natural that things not associated with the characters happen in the world (e.g. Commander Brage went on a rampage some time before player's party reached Nashkell, and the guards and some people know the commander, and were very surprised at his actions, guard that work under him mourn his sudden change, they put it as "All the guard are still grieving thet loss of of Commander Brage". Another example would be some guy named Prism cutting faces in the stone around mines of Nashkel - doesn't seem to add much to the story, but sure is a nice detail of the world around. A very nice touch works well towards the immersion of the world.
It does not even have to be a dynamic ever-changing world like some projects (e.g. dwarf fortress) try to achieve. Predefined story elements, flavour text, NPC disposition, dialogs, etc. are often just the right thing.
