= PLOT AND LORE

== Snippets

Here are snips of plot and lore elements that are to be sorted out later.

=== Lords of the Demonic Realm

==== The Trinity of Death

_[think about the names more, and possble naming scheme]_ +
Rozgob, the lord of destruction and chaos. +
Nezherteg, the lord of blood and slaughter. +
Dachometus, the lord of death and decay.

=== Other

_[think about the names more, and possble naming scheme]_ +
Sargal, the lord of warfare. +
<?>, the lord of pain and torture. +
Amakos, the lord of loss and grief. +
Tanesh, lord of gluttony and greed.

=== The Blade of the Slain

==== Description

The blade is rather long, but light enough for one-handed use and gradually gets much thinner towards the end. The decoration is inset, yet is reminiscent of blood vessels or a strange tree running throughout the entire blade with thin vessels flowing into a thicker one in the middle of the blade and then down into the guard. The hilt and the grip are marked with demonic symbols and branching decorations similar to those marking the blade, the blood vessels on the handle seemingly flow into a prominent glyph at the bottom of the hilt. The entire sword seems to be made of a single piece of a strange, dark-gray metal, the light reflected by it takes on a slightly crimson hue.

==== Lore

The blade, formed from blood by the demon lord Nezhertheg in the Halls of the Slain, steals some blood from each whom it cuts, and even small wounds made with this blade bleed heavily and heal slowly.
The blood of those cut down with this blade flows into the under-realm and fuels the feasts of Nezhertheg.
The blood that flows through this blade during slaughter can provide the wielder with vitality and power.

==== Ritual of Blood

There is a ritual that will bind the wielder and this blade. As soon as one has used this blade to slay another, and expresses a wish for more power and bloodshed, the demon lord Nezhertheg may respond, and through his dark will initiate the pact. The glyph at the bottom of the handle starts growing out and turns into a thin, long and sharp spike which the wielder is then instructed to pierce-through his throat from the front and from the side. If one has performed the instructions successfully, he then uses the blade to pierce his freshly fallen victim once more, the blade drinks much of the victims blood and Nezhertheg uses it to fully heal the wielder, including the fresh, heavily bleeding wound in the neck.

After this binding ritual is performed successfully, the blade starts consuming more blood from each cut it makes, and through that blood, provides vitality and strength to the user.
The performers neck seems completely healed, not even scars remain of the fresh wounds, but those bearing similar marks of Nezhertheg can always see four red dots on the neck, where the wounds had been, connected with thin red lines along which run tiny demonic glyphs. This marking is known as the Bloodletter's Collar, and is very difficult to detect by those not allied to Nezhertheg.

==== Ritual of Slaughter

When one has used this blade to fell about 20 or more victims. One can perform another ritual, this time one is instructed to prepare a living person as sacrifice and then pierce one's own heart seven times with the handle-spike, relying purely on the power of Nezhertheg to survive, when one pierces his heart for the seventh time, the spike breaks off and is absorbed into the performers body, there is now a pulsating cord attached between the bottom of the grip and the performers heart. Afterwards one proceeds to pierce the sacrificial sacrifice victim through the heart with the blade and is healed completely and the pulsating cord detaches the heart and retracts into the blade, the victim is left a dry mummy-like corpse.

With the completion of this ritual, the performer is granted more vitality, strength and power which temporarily grow even further, rather greatly, when blood is shed with the blade. The blade gets even more thirsty and deadly.
Now the wielder feels the blade as part of his own being and can use the power of the blood stored within to cause great pain and damage to those he cuts, he can also leave an invisible Blood-mark on one of his victims, that will last three days, if the wielder dies while there is a Blood-mark active, his corpse dries into ash within an hour and the wielder is formed anew from the blood-marked victims blood, close to the marked corpse.

After the ritual, the blade takes on a crimson hue and the blood-vessel markings that were seemingly engraved now fill-out and extrude slightly from the surface, they squirm subtly when the blade cuts flesh or touches blood. The wielder now has a slightly visible scar near his heart, and an invisible, but easily detectable, ring-shaped marking on the surrounding skin, filled with demonic glyphs. Fey-touched, demon-touched and otherwise non-mundane people can see this mark clearly, and it is nown as the Bloodletter's Heart.

NOTE: Nown only to the elect few is the secret of the Ritual of Slaughter. The hidden truth lies in that the performer binds not only his body, but also his spirit and soul to the under-realm of Nezhertheg. And thus, upon the final death of the performer of this unholy ritual, he is reborn as a demon of Nezhertheg, bereft of almost all will and previous memories, a purely evil thrall in the ranks of the Blood Letters.

==== Ritual of Life/Ritual of Madness

This ritual can be performed by those marked with a Bloodletter's Heart, but only after being offered immortality by Nezhertheg himself (e.g. as a voice after slaying someone, in a dream, or otherwise). It requires one to slay a baby younger than one year of age (360 days or less to be exact).

The ritual is performed by bleeding out one or multiple babies using the Blade of the Slain, then while in physical contact with baby blood (e.g. sitting in it naked) one bleeds oneself to death using the same blade. As soon as physical death of the body occurs, the performer is then spiritually taken to the under-realm of Nezhertheg into the feast of blood. After 24 hours have passed in the normal world, the performer is offered a contract, which he can sigh with his own blood. Then, whatever choice was made, the performer is returned to his body and wakes up, retaining all memories of the event.

If the contract is signed, the contractor is rewarded 5 years of life for each baby sacrificed in such fashion in exchange for eternally handing over part of his will to Nezhertheg. The contractor also gains knowledge about the hidden consequences of Ritual of Slaughter and possibly other secrets. The ritual can be repeated an unlimited amount of times to prolong one's life even further. While under the influence of this unholy life prolonging effect, the subject can not die of old age, and instead, ages backwards to around 24 one day at a time. The aging-backwards effect can be paused if the demon lord deems the circumstances necessary of his own accord or if contacted by the contractor, which for one bearing the mark of Bloodletter's Mind is an almost trivial exercise of will.

Handing over part of one's will manifests in, usually rare, direct requests from the demon. Sometimes one can also feel momentary, moderately hard to resist impulses or urges, and a more prolonged, subtle drive or wish for something, as result of a strong bond to demonic essence.

During the signing of the pact in the under-realm the subject receives a mark from the demon lord Nezhertheg himself. It is a subtle marking, and almost impossible to detect by those who do not bare the mark or are not among the elite servants of Nezhertheg, even other demon lords would miss it if not looking specifically, this mark is called the Bloodletter's Mind.

Those marked with Bloodletter's Mind, retain their memories and more of their own wicked will upon death, and often become lieutenants in the ranks of the Blood Letters. Also, those who bare this mark start to perceive somewhat like demons do, they notice manifestations of the demonic realm within their own, they see other bearers of Nezhertheg's marks, as well as demons, both in their natural guise and supernatural appearance simultaneously, and if close enough, they can even feel the presence of strong mark bearers and demons somewhat.

==== Additional Notes

After the final death of the wielder of the Blade of the Slain, most of the spiritual being of the blade leaves for the demonic realm, this exodus will take the appearance of blood leaking from the blade. The amount of blood that leaks out from the blade depends on the level of the bond with the wielder and the power he had, a blade that belonged to a carrier of the Bloodletter's Collar will likely produce but a few drops, while one that belonged to a transcendent elite of Nezhertheg may produce a few buckets. The bleeding will take up to a minute, after which the blood dries supernaturally quickly as the demonic essence leaves this plane of existence while the blade returns to its pre-ritual appearance almost immediately. If afterwards the blade is not touched by any person for a week - it melts into blood which then quickly dries up. The blade also melts if it has not cut flesh for 36 days, unless it has a partner in this plane of existence (i.e. someone had performed at least the Ritual of Blood with it).

==== Encounter Example

In some dark, dank underground place, where the wicked worshippers were performing rituals to their wicked god(s): You walk down a dark corridor, the smell of blood is sickeningly strong here and there is only one door nearby. You open the door to discover a rather small room, dim light from a small candle by the opposite wall barely manages to outline the stone walls and a small, square pool in the dead centre of the room. When you shed some light on the pool, you realise it is filled with blood. A soft, dark whisper touches your mind, subtly as if your own thought you hear "A gift is prepared for you in this pool, and it will prove very useful in your further endeavours." At the same moment your eyes glimpse something that seems like the very tip of a handle, barely sticking out of the liquid. Compelled, you reach out into the warm pool, the thing seems stuck, as your fingers tighten to pull it out, you feel unseen fingers briefly touch your hand, immediately the object turns lose, as if what was holding it just let go. You pull and in your blood-stained hand rests a sword. The blood in the pool starts rising until it spills over the edges and then recedes until it disappears completely, leaving only the blood stained ground around the little pool. You realise that the pool is just about six inches deep and wide, no way could this blade fit in there as it just did. Engraved on the bottom of the pool, is a strange glyph. The candle at the other end of the room burns out.
